---

- hosts: all
  become: true
  tasks:
          - name: update repository index
            dnf:
                    update_cache: yes
            when: ansible_distribution == "AlmaLinux"

          - name: update repository index
            apt:
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"
